name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml
      
import java.util.Scanner;
class PrimeAlt3rd
{
	public static void main(String[] args) 
	{
	    Scanner scn=new Scanner(System.in);
		System.out.println("Enter the number");
		int n=scn.nextInt();
		boolean printflag=true;
		int c=0;
		for(int i=1;i<=n;i++)
		{
		   int flag=1;
		   if(i==1)
		   continue;
		   else
		   {
		       for(int j=2;j<=i/2;j++)
		       {
		           if(i%j==0)
		           {
		           flag=0;
		           break;
		           }
			   }
		       
		       if(flag==1)
		       {
		           if(printflag)
		           {
		             System.out.println(i);
		             printflag=false;
		           }
		           else
		           c++;
		           if(c==2)
		           {
		               printflag=true;
		               c=0;
		           }
		       
		           
		       }
		       
		   }
		}
	}
}
